name: CI Workflow

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # This defines the operating system for the runner (Ubuntu in this case)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out the repository's code on the runner

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Action to set up Node.js environment
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Run `npm install` to install dependencies for your project

      - name: Run tests
        run: npm test  # Run tests using npm (you can change this to fit your test command)
