name: test run

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - master   # Run on pushes to the 'main' branch
  pull_request:
    branches:
      - master

  jobs:
  build:
    runs-on: window-latest 

 steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2   # This action checks out your repository's code

      # Step 2: Set up Node.js (if you're working with a Node.js project)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set the version of Node.js to use (adjust based on your needs)

      # Step 3: Install dependencies (e.g., npm install)
      - name: Install dependencies
        run: npm install   # If you're using npm, replace with 'yarn install' if you're using Yarn

      # Step 4: Run tests
      - name: Run tests
        run: npm test   
